### ISSUE TITLE
Always cast _id to ObjectID

### ISSUE THREAD

**Issue by maxsh8x** [e-oj/Fawn#32]
I have _id as number. Can i disable this behavior?

**Comment by e-oj** [comment]
Right now, no, you can't disable that behavior. But I see what you mean; an option like that would eb useful. This could be added to the next release.

**Comment by e-oj** [comment]
The workaround would be to store your integer _id in a different field ("id" maybe?)

**Comment by laosb** [comment]
Hello, I'm trying to use this package with Meteor - which uses `String` for `_id`s. I wonder how hard will be to implement this change?

**Comment by e-oj** [comment]
This has been fixed. Upgrade your Fawn version and it should be fine. Let me know if it isn't.

**Comment by laosb** [comment]
if i try update with _id field it still emits an error; anyway i dont use _id for now, so everything works now. i will let you know if i could still see this problem later. thanks!

**Comment by e-oj** [comment]
You're getting update errors with _id? That shouldn't be happening. What's the error? also, can you share the code?

**Comment by laosb** [comment]
it emits an hard-to-understand max call stack size exceeded. it could be fawn's fault but also can be mine. further investigation is on its way but i would just take one day off on this new year's day - happy new year from china!

**Comment by e-oj** [comment]
Happy new year to you too 🎉

**Comment by laosb** [comment]
@e-oj Figured out. I tried to return the result of `task.run()`, which includes cyclic ref. Meteor tried to stringify it before sending to client, and that caused a maximum call stack size exceed. My fault! Safe to close now. Thank you for your patience!

**Comment by e-oj** [comment]
No problem 👍
